import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pluginDocsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'references',
    },
  ],
};

export default sidebars;
